# Generated by Django 4.2.27 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_workspacemember_explored_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporterhistory',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exporterhistory',
            name='processed_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exporterhistory',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
